### ISSUE TITLE
暂时没有打算加浊音/半浊音/拗音吗

### ISSUE THREAD

**Issue by yuchiXiong** [a-wing/japanese-50-sounds#2]
rt，看了下 data.ts 里好像只有清音？

**Comment by a-wing** [comment]
因为后来发现 duolingo 里面有类似的功能。然后我就去用 duolingo 了（

（应该把这个坑都填完（（（

**Comment by yuchiXiong** [comment]
噗 好吧hhhh😂😂😂

**Comment by a-wing** [comment]
坑填完了）

<img width="593" alt="Screenshot 2023-03-30 at 00 02 55" src="https://user-images.githubusercontent.com/18189138/228599036-34adf2c3-08f0-4547-936c-36f6e95afda8.png">
